ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS lineId VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS origin VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS destination VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS airline VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS cabinClass VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS assignedStaff VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS adminNotes TEXT NULL,
  ADD COLUMN IF NOT EXISTS paymentStatus VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
